name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Allure Playwright Reporter
        run: npm install -D allure-playwright

      - name: Cache browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Start backend server
        run: node server.js > server.log 2>&1 &

      - name: Wait for server
        run: |
          for i in {1..20}; do
            curl -s http://127.0.0.1:3000/health && exit 0
            sleep 1
          done
          exit 1

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      # Install Allure CLI
      - name: Install Allure CLI
        if: always()
        run: npm install -g allure-commandline

      # Generate Allure Report (this creates the colorful UI)
      - name: Generate Allure Report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      # Upload Final Allure Report (colorful one)
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/